version: '3'
services:
  app:
    image: ai-agent-ui
    container_name: ai-agent-ui
    ports:
      - "80:80"   # Map HTTP port
      - "443:443" # Map HTTPS port
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - ai-agent-network

networks:
  ai-agent-network:
    driver: bridge